steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/app-menu-427017/menu-app-frontend'
  - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/app-menu-427017/menu-app-frontend'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'menu-app'
  - '--image=gcr.io/app-menu-427017/menu-app-frontend'
  - '--platform=managed'
  - '--region=europe-southwest1'
  - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY
